# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    shortener:
        class: AppBundle\Service\Shortener
        arguments: ["@snc_redis.default", "%base_redirection_url%", "%redis_key_prefix%"]
