# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    shortener:
        class: AppBundle\Service\Shortener
        arguments: ["@snc_redis.default", "@uri_provider", "%base_redirection_url%", "%redis_key_prefix%"]
    uri_provider:
        class: AppBundle\Service\UriProvider
        arguments: ["@snc_redis.default", "%redis_key_prefix%"]
    app.api_controller:
        class: AppBundle\Controller\ApiController
        arguments: ["@shortener", "%base_redirection_url%", "%secret"]
    app.web_controller:
        class: AppBundle\Controller\WebController
        arguments: ["@router", "@templating", "@form.factory", "@event_dispatcher", "@session", "@shortener", "%base_redirection_url%"]
    app.visitor_subscriber:
        class: AppBundle\EventSubscriber\VisitorSubscriber
        arguments: ["@snc_redis.default", "%redis_key_prefix%"]
        tags:
            - { name: kernel.event_subscriber }
