parameters:
    base_redirection_url: "http://localhost"
    redis_key_prefix: ''

services:
    app.redis_mock:
        class: AppBundle\Service\RedisMock
    shortener:
        class: AppBundle\Service\Shortener
        arguments: ["@app.redis_mock", "@uri_provider", "%base_redirection_url%", "%redis_key_prefix%"]
    uri_provider:
        class: AppBundle\Service\UriProvider
        arguments: ["@app.redis_mock", "%redis_key_prefix%"]
    app.api_controller:
        class: AppBundle\Controller\ApiController
        arguments: ["@shortener", "%base_redirection_url%", "%secret"]
    app.web_controller:
        class: AppBundle\Controller\WebController
        arguments: ["@router", "@templating", "@form.factory", "@event_dispatcher", "@session", "@shortener", "%base_redirection_url%"]
    app.visitor_subscriber:
        class: AppBundle\EventSubscriber\VisitorSubscriber
        arguments: ["@app.redis_mock", "%redis_key_prefix%"]
        tags:
            - { name: kernel.event_subscriber }
